platform :ios, '17.0'

# Specify the Xcode project path
project 'SeatclubApp/SeatclubApp.xcodeproj'

target 'SeatclubApp' do
  use_frameworks!
  
  # Completely self-contained framework - no external dependencies
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
